version: '3'

services:
    robot:
        image: dukerobotics/robosub-ros
        container_name: robot
        privileged: true
        ports: 
            - 2200:2200
            - 11311:11311
        networks:
            local_net:
                ipv4_address: 192.168.1.1
        tty: true
        command: sudo su duke
                 cd ~/dev && \
                 git clone https://github.com/DukeRobotics/robosub-ros.git && \
                 source /opt/ros/kinetic/setup.bash && \
                 cd robosub-ros/catkin_ws && \
                 catkin build
                 source devel/setup.bash
                 roscore &
            


    landside:
        image: dukerobotics/robosub-ros:landside
        container_name: landside
        depends_on:
            - robot
        privileged: true
        network_mode: host
        tty: true
        command: sudo su duke
                 cd ~/dev && \
                 git clone https://github.com/DukeRobotics/robosub-ros.git && \
                 source /opt/ros/kinetic/setup.bash && \
                 source /opt/ros/kinetic/setup_pool.bash && \
                 cd robosub-ros/catkin_ws && \
                 catkin build
                 source devel/setup.bash

networks:
    local_net:
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
        
