name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: dukerobotics/robosub-ros:arm64
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          export DOCKER_CLI_EXPERIMENTAL=enabled
          sudo systemctl restart docker
          docker info
          docker buildx ls
      
      - name: Build image
        run: docker buildx build --platform linux/arm64 -t dukerobotics/robosub-ros:arm64 --load .
      
      - name: Test
        working-directory: latest
        run: docker-compose --file clone-and-build.test.yml run sut
      
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u neildhar --password-stdin
          docker push dukerobotics/robosub-ros:arm64
          docker manifest create dukerobotics/robosub-ros:latest dukerobotics/robosub-ros:arm64 dukerobotics/robosub-ros:amd64
          docker manifest push -p dukerobotics/robosub-ros:latest
