name: build

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  core-arm64:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dukerobotics/robosub-ros:core-arm64
      TARGETPLATFORM: linux/arm64
      FOLDER_NAME: core
      BASE_IMAGE: ros:kinetic-ros-core-xenial
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment and build
        run: |
          ./.github/workflows/build.sh
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker push ${IMAGE_NAME}
      - name: Save image
        run: |
          docker save ${IMAGE_NAME} | gzip > arm64.tar.gz
      - name: Create artifact from image
        uses: actions/upload-artifact@v1
        with:
          name: arm64
          path: arm64.tar.gz

  core-amd64:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dukerobotics/robosub-ros:core-amd64
      TARGETPLATFORM: linux/amd64
      FOLDER_NAME: core
      BASE_IMAGE: ros:kinetic-ros-core-xenial
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment and build
        run: |
          ./.github/workflows/build.sh
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker push ${IMAGE_NAME}
      - name: Save image
        run: |
          docker save ${IMAGE_NAME} | gzip > amd64.tar.gz
      - name: Create artifact from image
        uses: actions/upload-artifact@v1
        with:
          name: amd64
          path: amd64.tar.gz

  onboard-arm64:
    runs-on: ubuntu-latest
    needs: core-arm64
    env:
      IMAGE_NAME: dukerobotics/robosub-ros:onboard-arm64
      TARGETPLATFORM: linux/arm64
      FOLDER_NAME: latest
      BASE_IMAGE: dukerobotics/robosub-ros:core-arm64
    steps:
      - uses: actions/checkout@v2
      - name: Get core image
        uses: actions/download-artifact@v1
        with: 
          name: arm64
      - name: Load core image
        run: |
          docker load < ./arm64/arm64.tar.gz
          rm -rf arm64
      - name: Setup environment and build
        run: |
          ./.github/workflows/build.sh
          ./.github/workflows/test.sh
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker push ${IMAGE_NAME}

  onboard-amd64:
    runs-on: ubuntu-latest
    needs: core-amd64
    env:
      IMAGE_NAME: dukerobotics/robosub-ros:onboard-amd64
      TARGETPLATFORM: linux/amd64
      FOLDER_NAME: latest
      BASE_IMAGE: dukerobotics/robosub-ros:core-amd64
    steps:
      - uses: actions/checkout@v2
      - name: Get core image
        uses: actions/download-artifact@v1
        with: 
          name: amd64
      - name: Load core image
        run: |
          docker load < ./amd64/amd64.tar.gz
          rm -rf amd64
      - name: Setup environment and build
        run: |
          ./.github/workflows/build.sh
          ./.github/workflows/test.sh
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker push ${IMAGE_NAME}

  push:
    runs-on: ubuntu-latest
    needs: [main-arm64, main-amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Push images to latest
        if: github.event_name == 'push'
        run: |
          ./.github/workflows/setup.sh
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker buildx imagetools create --tag dukerobotics/robosub-ros:core dukerobotics/robosub-ros:core-amd64 dukerobotics/robosub-ros:core-arm64
          docker buildx imagetools create --tag dukerobotics/robosub-ros:latest dukerobotics/robosub-ros:onboard-amd64 dukerobotics/robosub-ros:onboard-arm64
      - name: Cleanup artifacts
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/workflows/cleanup.sh
  
  landside:
    runs-on: ubuntu-latest
    needs: core-amd64
    env:
      IMAGE_NAME: dukerobotics/robosub-ros:landside
      BASE_IMAGE: dukerobotics/robosub-ros:core-amd64
    steps:
      - uses: actions/checkout@v2 
      - name: Get core image
        uses: actions/download-artifact@v1
        with: 
          name: amd64
      - name: Load core image
        run: |
          docker load < ./amd64/amd64.tar.gz
          rm -rf amd64
      - name: Setup environment and build
        working-directory: 
        run: |
          cd landside
          docker build --build-arg BASE_IMAGE=${BASE_IMAGE} -t  ${IMAGE_NAME} .
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker push ${IMAGE_NAME}
