name: build

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  arm64:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dukerobotics/robosub-ros:arm64
      TARGETPLATFORM: linux/arm64
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment and build
        run: |
          ./.github/workflows/setup.sh
          ./.github/workflows/build.sh
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker push ${IMAGE_NAME}

  amd64:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dukerobotics/robosub-ros:amd64
      TARGETPLATFORM: linux/amd64
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment and build
        run: |
          ./.github/workflows/setup.sh
          ./.github/workflows/build.sh
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker push ${IMAGE_NAME}
  push:
    runs-on: ubuntu-latest
    needs: [arm64, amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Push images to latest
        if: github.event_name == 'push'
        run: |
          ./.github/workflows/setup.sh
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker buildx imagetools create --tag dukerobotics/robosub-ros:latest dukerobotics/robosub-ros:amd64 dukerobotics/robosub-ros:arm64

  simulation:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dukerobotics/robosub-ros:simulation
    needs: push
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment and build
        working-directory: 
        run: |
          cd simulation
          docker build -t ${IMAGE_NAME} .
      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_BOT_TOKEN }}" | docker login -u dukeroboticsbot --password-stdin
          docker push ${IMAGE_NAME}